//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bilibili_Live_Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bilibili_Live_Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap panel_beigeLight {
            get {
                object obj = ResourceManager.GetObject("panel_beigeLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_01 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_02 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_03 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_04 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_05 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_06 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_07 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_08 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_09 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_10 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_100 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_101 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_102 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_103 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_104 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_104", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_105 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_105", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_106 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_107 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_107", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_108 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_108", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_109 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_109", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_11 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_110 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_110", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_111 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_111", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_112 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_112", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_113 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_113", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_114 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_114", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_115 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_115", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_116 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_12 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_13 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_14 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_15 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_16 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_17 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_18 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_19 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_20 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_21 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_22 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_23 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_24 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_25 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_26 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_27 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_28 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_29 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_30 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_31 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_32 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_33 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_34 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_35 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_36 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_37 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_38 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_39 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_40 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_41 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_42 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_43 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_44 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_45 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_46 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_47 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_48 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_49 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_50 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_51 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_52 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_52", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_53 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_54 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_54", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_55 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_56 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_56", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_57 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_57", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_58 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_58", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_59 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_59", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_60 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_61 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_62 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_62", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_63 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_63", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_64 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_65 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_66 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_66", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_67 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_67", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_68 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_68", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_69 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_69", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_70 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_71 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_72 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_73 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_73", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_74 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_74", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_75 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_75", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_76 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_76", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_77 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_77", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_78 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_78", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_79 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_79", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_80 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_81 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_82 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_83 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_83", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_84 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_84", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_85 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_85", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_86 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_86", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_87 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_87", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_88 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_88", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_89 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_89", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_90 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_91 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_92 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_93 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_94 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_94", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_95 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_96 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_97 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_97", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_98 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap svg_sprite_e15d8c3_99 {
            get {
                object obj = ResourceManager.GetObject("svg_sprite_e15d8c3_99", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
